Update netdata

diff --git a/mods/apps/netdata b/mods/apps/netdata
--- a/mods/apps/netdata
+++ b/mods/apps/netdata
@@ -1,7 +1,15 @@
 #!/bin/bash
 
-# Source the configuration file to get the appdata_path
-source /pg/config/$app_name.cfg
+# Specify the config file path
+config_path="/pg/config/$1.cfg"
+
+# Source the configuration file to get the appdata_path and app_name
+if [[ -f "$config_path" ]]; then
+    source "$config_path"
+else
+    echo "Error: Configuration file not found at $config_path."
+    exit 1
+fi
 
 # Deploy Netdata with the updated paths
 docker run -d --name="$app_name" \
