Update plex

diff --git a/mods/apps/plex b/mods/apps/plex
--- a/mods/apps/plex
+++ b/mods/apps/plex
@@ -7,9 +7,24 @@
 ##### Plex Token: null
 ##### Version Tag: latest
 
+# ANSI color codes
+RED="\033[0;31m"
+GREEN="\033[0;32m"
+NC="\033[0m" # No color
+
+# Define config path and app name globally
+app_name="plex"
+config_path="/pg/config/${app_name}.cfg"
+
 #### Token
 token() {
     clear
+    
+    # Source the configuration file to get the current plex_token value
+    if [[ -f "$config_path" ]]; then
+        source "$config_path"
+    fi
+
     echo "Current Token: $plex_token"
     echo -e "Note: Changing the token will stop the Docker containers and require manual redeployment."
     echo -e "\nPlease enter your new Plex Token from https://plex.tv/claim"
@@ -43,14 +58,18 @@ token() {
 # Function to deploy the Docker container for the app
 deploy_container() {
 
-    # Specify config file path and source information
-    config_path="/pg/config/${app_name}.cfg"
-    source "$config_path"
+    # Source the configuration file to get the appdata_path and plex_token
+    if [[ -f "$config_path" ]]; then
+        source "$config_path"
+    else
+        echo "Error: Configuration file not found at $config_path."
+        exit 1
+    fi
 
     # Check and update the Plex token if necessary
     if [[ "$plex_token" == "null" || ( ! "$plex_token" =~ ^claim && "$plex_token" != "no-token" ) ]]; then
         clear
-        echo -e "The Plex Token needs to be updated"
+        echo -e "${RED}The Plex Token needs to be updated${NC}"
         echo -e "A. Please enter your Plex Token from https://plex.tv/claim"
         echo -e "B. To skip entering a token, type: ${RED}no-token${NC}\n"
         while true; do
@@ -64,7 +83,7 @@ deploy_container() {
             else
                 echo "Invalid token format. Please ensure the token starts with 'claim-' or type 'no-token'."
                 clear
-                echo -e "The Plex Token needs to be updated"
+                echo -e "${RED}The Plex Token needs to be updated${NC}"
                 echo -e "A. Please enter your Plex Token from https://plex.tv/claim"
                 echo -e "B. To skip entering a token, type: ${RED}no-token${NC}\n"
             fi
