Update apps_interface

diff --git a/mods/scripts/apps_interface b/mods/scripts/apps_interface
--- a/mods/scripts/apps_interface
+++ b/mods/scripts/apps_interface
@@ -52,6 +52,19 @@ apps_interface() {
         fi
     }
 
+    # Function to get or set the port number
+    get_or_set_port_number() {
+        if ! grep -q '^port_number=' "$config_path"; then
+            port_number=$(awk '/# Default Port:/ {print $NF}' "$app_path")
+            [[ -n "$port_number" ]] && echo "port_number=${port_number}" >> "$config_path" || {
+                echo "Error: Default port not found in $app_path."
+                exit 1
+            }
+        else
+            source "$config_path"
+        fi
+    }
+
     # Function to change the port number
     change_port_number() {
         clear
